# tomcat配置
server:
  port: 80

# 全文检索配置
lucene:
  index:
    path: "/usr/server/lucene"

# Mybatis配置
mybatis:
  type-aliases-package: com.ali.nainai.entity

# Spring配置（包括数据源，jpa, freemarker, thymeleaf的配置）
spring:
  datasource:
    url: "jdbc:mysql://120.79.36.196:3306/ali_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull"
    username: "root"
    password: "alinainai../"
    driver-class-name: "com.mysql.jdbc.Driver"

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        hbm2ddl:
          auto: update

  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: ".ftl"
    template-loader-path: "classpath:/templates/"
    settings:
      template_update_delay: "0"
      default_encoding: "utf-8"
      classic_compatible: true
      date_format: "yyyy-MM-dd"
      time_format: "HH:mm:ss"
      datetime_format: "yyyy-MM-dd HH:mm:ss"

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: utf-8
    content-type: text/html
    suffix: .html
    mode: HTML5



